name: ci
on:
  pull_request:
  push:
    branches:
      - main
      - release/*
      - snapshot/*
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref_name != 'main' }}

jobs:
  build-frontend:
    name: "build-frontend"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup_environment
        with:
          enable_npm: true

      - name: Check Tag
        ## This step is verifying that the tag follow the semver
        ## It is only triggered when a tag is created
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'v') }}
        run: ./scripts/release.sh --check-version "${{ github.ref_name }}"

      - name: Check libraries version
        ## This step is verifying that the version of each package is matching the tag
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'v') }}
        run: ./scripts/ui_release.sh --check-package "${{ github.ref_name }}"

      - name: Use snapshot version
        ## This step only runs for "snapshot" branches starting with "snapshot/"
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'snapshot/') }}
        run: ./scripts/ui_release.sh --snapshot-version "${{ github.ref_name }}" "${{ github.sha }}"

      - name: Install UI deps
        run: cd ./ui && npm install
      - name: Build the app and all packages
        run: cd ./ui && npm run build
      - name: store react production build
        uses: actions/upload-artifact@v3
        with:
          name: ui-libs
          path: |
            ui/**/dist
            !ui/node_modules

  e2e:
    name: "end-to-end-tests"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.28.0-focal
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_environment
        with:
          enable_npm: true
      - name: Install UI deps
        run: cd ./ui && npm install
      - name: Run app in dev mode
        run: cd ./ui && npm run start &
      - name: Run Playwright tests and update snapshots
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          cd ./ui
          npm run e2e:updateSnapshots 
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add e2e/tests
          git commit -m "Update e2e snapshots"
          git push
      - name: Run Playwright tests and fail on snapshot differences
        if: ${{ github.event_name == 'push' }}
        run: cd ./ui && npm run e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ui/e2e/playwright-report/
          retention-days: 30

  libs-release:
    name: "libs-release"
    needs: "build-frontend"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup_environment
        with:
          enable_npm: true
      - name: Download react build
        uses: actions/download-artifact@v3
        with:
          name: ui-libs
          path: ui
      - name: Copy files before publishing libs
        run: ./scripts/ui_release.sh --copy
      - name: Publish dry-run libraries
        if: ${{ github.event_name == 'pull_request' || github.ref_name == 'main' }}
        run: ./scripts/ui_release.sh --publish dry-run
      - name: Publish libraries
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'v') }}
        run: ./scripts/ui_release.sh --publish
        env:
          # The setup-node action writes an .npmrc file with this env variable
          # as the placeholder for the auth token
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish snapshot libraries
        ## This step only runs for "snapshot" branches starting with "snapshot/"
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'snapshot/') }}
        ## The previous job that is building the UI assets doesn't persist the different `package.json`
        ## files that were modified by the script. In order to be able to publish the snapshot, we
        ## need to ensure the different `package.json` files contain the correct version.
        ## That's why we are running the script again to bump the snapshot version.
        run: |
          ./scripts/ui_release.sh --snapshot-version "${{ github.ref_name }}" "${{ github.sha }}"
          cd ./ui && npm install && cd ..
          ./scripts/ui_release.sh --publish-snapshot "${{ github.ref_name }}"
        env:
          # The setup-node action writes an .npmrc file with this env variable
          # as the placeholder for the auth token
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:
    name: "go and github release"
    needs: "build-frontend"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup_environment
        with:
          enable_go: true
      - name: Download react build
        uses: actions/download-artifact@v3
        with:
          name: ui-libs
          path: ui
      - name: Extract Changelog
        run: make generate-changelog
      - name: install goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          install-only: true
      - name: Build Go binaries
        run: make cross-build
      - name: Publish Release
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'v') }}
        run: make cross-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
